language: java

jdk:
  - oraclejdk7

before_script:
  - sudo apt-get update -qq
  - sudo add-apt-repository -y ppa:juan457/zorba
  - sudo apt-get update
  - sudo apt-get install zorba

script: 
  - jdk_switcher use oraclejdk7
  - bin/test.sh
