language: java

jdk:
  - oraclejdk7

before_script:
  - sudo apt-get update -qq
  - sudo add-apt-repository ppa:juan457/zorba
  - sudo apt-get update
  - sudo apt-get install zorba

script: 
  - jdk_switcher use oraclejdk7
  - zorba -i -f -q xbin/zorba.xqy -e marcxmluri:="http://lccn.loc.gov/61008194/marcxml" -e serialization:="rdfxml" -e baseuri:="http://bibframe.org/"
